server:
    port: 8280
spring:
    datasource:
        name: store-rdbms
        url: jdbc:sqlserver://192.168.56.2:1433;databaseName=VOM;SendStringParametersAsUnicode=true
        username: vomapp
        password: admin
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        platform: mssql
        initialization-mode: ALWAYS
        continue-on-error: true
        jpa:
            generate-ddl: true
            hibernate:
                ddl-auto: none
                dialect: org.hibernate.dialect.SQLServer2005Dialect
            show-sql: true
    jackson.serialization.write_dates_as_timestamps: false
management:
    endpoints.enabled-by-default: true
    endpoint.beans.enabled: true
logging:
    file:
        name: ./logs/vom-billing-manager.log
        
amazon:
    dynamodb.endpoint: dynamodb.ap-northeast-1.amazonaws.com
    aws:
        accesskey: AKIAWUAR7BE57W3TU4US
        secretkey: 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