spring:
    datasource:
        name: store-rdbms
        url: jdbc:h2:mem:testdb
        username: vomapp
        password: admin
        driver-class-name: org.h2.Driver
        platform: h2
        initialization-mode: ALWAYS
        continue-on-error: true
        jpa:
            generate-ddl: true
            hibernate:
                ddl-auto: none
                dialect: org.hibernate.dialect.H2Dialect
            show-sql: true
    jackson.serialization.write_dates_as_timestamps: false
        
amazon:
    dynamodb.endpoint: dynamodb.ap-northeast-1.amazonaws.com
    aws:
        accesskey: AKIAWUAR7BE57W3TU4US
        secretkey: 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